import { FaBrain, FaQuestionCircle, FaFileDownload, FaUserMd, FaLock } from "react-icons/fa";

const features = [
  {
    title: "Smart AI Diagnosis",
    description:
      "Sehat uses intelligent algorithms to understand your health symptoms and suggest initial assessments.",
    icon: <FaBrain className="text-3xl text-cyan-400" />,
  },
  {
    title: "Personalized Questions",
    description:
      "Receive adaptive and relevant questions tailored to your specific health issues.",
    icon: <FaQuestionCircle className="text-3xl text-cyan-400" />,
  },
  {
    title: "PDF Report Download",
    description:
      "Get a detailed, downloadable health report generated by our AI system — ready for sharing or printing.",
    icon: <FaFileDownload className="text-3xl text-cyan-400" />,
  },
  {
    title: "Trusted Doctor Referrals",
    description:
      "Get suggestions for verified doctors or specialists based on your condition and location.",
    icon: <FaUserMd className="text-3xl text-cyan-400" />,
  },
  {
    title: "Data Privacy & Security",
    description:
      "All user data is encrypted and protected — your health information stays confidential.",
    icon: <FaLock className="text-3xl text-cyan-400" />,
  },
];

const Features = () => {
  return (
    <section className="min-h-screen px-6 py-20 bg-gray-950 text-white">
      <div className="max-w-7xl mx-auto text-center">
        <h2 className="text-4xl font-bold mb-6 text-cyan-400">Features of Sehat</h2>
        <p className="text-lg text-gray-300 mb-12">
          Designed to deliver smart, secure, and efficient health assistance powered by AI.
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-10">
          {features.map((feature, index) => (
            <div
              key={index}
              className="bg-white/10 border border-white/20 rounded-2xl p-6 backdrop-blur-md hover:scale-105 transition-transform text-left"
            >
              <div className="mb-4">{feature.icon}</div>
              <h3 className="text-xl font-semibold mb-2 text-white">{feature.title}</h3>
              <p className="text-sm text-gray-300">{feature.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Features;